from __future__ import annotations

from typing import Protocol, runtime_checkable

from ..sandbox import DirEntry


@runtime_checkable
class UserDirBackend(Protocol):
    async def read_file(self, path: str) -> bytes: ...
    async def write_file(self, path: str, data: bytes) -> None: ...
    async def list_dir(self, path: str) -> list[DirEntry]: ...
    async def exists(self, path: str) -> bool: ...
    async def remove(self, path: str, *, recursive: bool = False) -> None: ...
