"""pagentv4 —— 顶层门面。

模块分层：
- core/       AgentCore + Message + Provider + Tool + Event
- ithread/    IThread Protocol + ThreadSpec（Thread 层抽象）
- conversation/ ConversationStore（对话持久化）
- runtime/    Runner + Thread（编排 + 持久化）
- sandbox/    伴身电脑（Backend Protocol + Sandbox 门面 + tools 适配）
- adapters/   与外部协议的编解码（当前只有 ACP）

用户面：`from pagentv4 import AgentCore, Runner, ...` 是推荐写法，
`Agent` 作为兼容别名保留。
子包深路径也稳定可用（`from pagentv4.core import ...`）。
"""

from .adapters import decode_event_line, encode_event_line
from .conversation import (
    ConversationStore,
    JsonlConversationStore,
    SqliteConversationStore,
    default_conversations_root,
)
from .core import (
    PROVIDER_TYPES,
    Agent,
    AgentCore,
    AssistantChunk,
    AudioUrl,
    DeepSeek,
    Event,
    FunctionTool,
    ImageAttachment,
    ImageUrl,
    Kimi,
    LongCat,
    Message,
    Messages,
    MiMo,
    Ollama,
    Provider,
    ProviderHandoff,
    ProviderIdentity,
    ProviderKind,
    ProviderProtocol,
    ReasoningDelta,
    RunBegin,
    RunEnd,
    Sglang,
    StopReason,
    TextChunk,
    TextDelta,
    ThinkingChunk,
    ToolCall,
    ToolCallBegin,
    ToolOutput,
    ToolResult,
    TurnBegin,
    TurnEnd,
    TurnResult,
    UserChunk,
    Vllm,
    build_provider,
    provider_api_key_env,
    provider_base_url,
    provider_requires_api_key,
    reply_text,
    resolve_active_provider_identity,
    to_openai_tools,
    tool,
)
from .ithread import IThread, SubAgentSpec, ThreadSpec, validate_thread_id
from .runtime import (
    RUN_PHASE_LABELS,
    AgentRunner,
    ArunReturnType,
    BaseRunner,
    ChatAgent,
    ChatRunner,
    CodeAgent,
    CodeRunner,
    EventHandler,
    ImageInput,
    PostToolHookContext,
    Runner,
    RunPhase,
    RunState,
    Thread,
    ThreadAgent,
    ToolDecision,
    ToolHookContext,
    ToolHooks,
    VanillaAgent,
    VanillaRunner,
    default_threads_root,
)
from .sandbox import (
    Backend,
    BackendGuard,
    BackendIdentity,
    CommandResult,
    DirEntry,
    LocalBackend,
    Sandbox,
    SandboxDeadError,
    SandboxError,
    SandboxLimits,
    SandboxNotStartedError,
    SandboxSpec,
    SshConnection,
    build_backend,
    build_computer_description,
    build_sandbox_tools,
)
from .skills import (
    Skill,
    SkillDiscoveryError,
    SkillRegistry,
    build_skills_system_prompt,
    default_skill_roots,
    load_skill,
    load_skills_from_root,
    make_use_skill_tool,
)

__all__ = [
    "Agent",
    "AgentCore",
    "AgentRunner",
    "ArunReturnType",
    "AssistantChunk",
    "AudioUrl",
    "Backend",
    "BackendGuard",
    "BackendIdentity",
    "BaseRunner",
    "ChatAgent",
    "ChatRunner",
    "CodeAgent",
    "CodeRunner",
    "CommandResult",
    "ConversationStore",
    "DeepSeek",
    "DirEntry",
    "Event",
    "EventHandler",
    "FunctionTool",
    "IThread",
    "ImageAttachment",
    "ImageInput",
    "ImageUrl",
    "JsonlConversationStore",
    "Kimi",
    "LocalBackend",
    "LongCat",
    "Message",
    "Messages",
    "MiMo",
    "Ollama",
    "PROVIDER_TYPES",
    "PostToolHookContext",
    "Provider",
    "ProviderHandoff",
    "ProviderIdentity",
    "ProviderKind",
    "ProviderProtocol",
    "ReasoningDelta",
    "RunBegin",
    "RunEnd",
    "RunPhase",
    "RUN_PHASE_LABELS",
    "RunState",
    "Runner",
    "Sandbox",
    "SandboxDeadError",
    "SandboxError",
    "SandboxLimits",
    "SandboxNotStartedError",
    "SandboxSpec",
    "Sglang",
    "SshConnection",
    "Skill",
    "SkillDiscoveryError",
    "SkillRegistry",
    "SqliteConversationStore",
    "StopReason",
    "TextChunk",
    "TextDelta",
    "ThinkingChunk",
    "Thread",
    "ThreadAgent",
    "ThreadSpec",
    "SubAgentSpec",
    "ToolCall",
    "ToolCallBegin",
    "ToolDecision",
    "ToolHookContext",
    "ToolHooks",
    "ToolOutput",
    "ToolResult",
    "TurnBegin",
    "TurnEnd",
    "TurnResult",
    "UserChunk",
    "VanillaAgent",
    "VanillaRunner",
    "Vllm",
    "build_provider",
    "provider_api_key_env",
    "provider_base_url",
    "provider_requires_api_key",
    "build_backend",
    "build_computer_description",
    "build_sandbox_tools",
    "build_skills_system_prompt",
    "decode_event_line",
    "default_conversations_root",
    "default_skill_roots",
    "default_threads_root",
    "encode_event_line",
    "load_skill",
    "load_skills_from_root",
    "make_use_skill_tool",
    "reply_text",
    "resolve_active_provider_identity",
    "to_openai_tools",
    "tool",
    "validate_thread_id",
]
