from __future__ import annotations

from typing import Any, Protocol, TypeAlias, runtime_checkable

SessionMessage: TypeAlias = dict[str, Any]


@runtime_checkable
class SessionBackend(Protocol):
    def save(self, session_id: str, messages: list[SessionMessage]) -> None: ...
    def load(self, session_id: str) -> list[SessionMessage]: ...
    def list(self) -> list[str]: ...
    def delete(self, session_id: str) -> None: ...
    def close(self) -> None: ...
